const $=id=>document.getElementById(id);const q=s=>document.querySelector(s);const qa=s=>document.querySelectorAll(s);
let night=1,elapsed=0,timer=null,playing=false,view='front',camera='cam01',energy='camera',energyBusy=false,energyBlockedUntil=0,rightDoorClosed=false,backupDone=false,wireStep=0,leverStart=0,mindLevel=70,mindTimer=null;
const configs={1:['lichi'],2:['lichi','pancake'],3:['lichi','pancake','nemka'],4:['pancake','delta','nemka'],5:['lichi','delta','lizka','nemka'],6:['kyu','lichi','pancake','nemka','lizka'],7:['lichi','pancake','nemka','delta','kyu','kashatan','charlotte','lizka','mindflayer'],8:['lichi','pancake','nemka','delta','kyu','kashatan','charlotte','lizka','mindflayer'],9:['nemka','lichi','pancake','delta','kyu','kashatan','charlotte','lizka','mindflayer'],10:['nemka','pancake','delta','kyu','kashatan','charlotte','lizka','mindflayer'],11:['nemka','lichi','delta','kyu','kashatan','charlotte','lizka','mindflayer'],12:['nemka','lichi','pancake','delta','kyu','kashatan','charlotte','lizka','mindflayer'],13:['nemka','lichi','pancake','delta','kyu','kashatan','charlotte','lizka','mindflayer']};
const state={nemka:0,lichi:0,pancake:0,kyu:0,kashatan:0,charlotte:0,lizka:0,mindflayer:0,delta:0};
function active(n){return (configs[night]||configs[13]).includes(n)}
function snd(id){const a=$(id);if(!a)return;try{a.currentTime=0;a.play().catch(()=>{})}catch(e){}}
function stop(id){const a=$(id);if(a){a.pause();a.currentTime=0}}
function hideAll(){qa('.screen').forEach(x=>x.classList.add('hidden'));$('game').classList.add('hidden')}
function menu(){clearInterval(timer);clearInterval(mindTimer);playing=false;hideAll();$('mainMenu').classList.remove('hidden');stop('humAudio')}
function start(n=night){night=n;hideAll();$('phoneNight').textContent='NIGHT '+night;$('phoneScreen').classList.remove('hidden');snd('phoneAudio')}
function begin(){hideAll();$('game').classList.remove('hidden');resetGame();playing=true;snd('humAudio');timer=setInterval(tick,1000);}
function resetGame(){elapsed=0;view='front';camera='cam01';energy='camera';energyBusy=false;energyBlockedUntil=0;rightDoorClosed=false;backupDone=false;wireStep=0;mindLevel=70;Object.keys(state).forEach(k=>state[k]=0);qa('.panel,.overlay').forEach(x=>x.classList.add('hidden'));$('rightDoor').classList.remove('closed');$('rightDoorButton').textContent='ЗАКРЫТЬ';$('time').textContent='12:00 AM';$('night').textContent='NIGHT '+night;$('status').textContent='ОФИС';$('upperVent').classList.remove('upperVentActive');qa('#upperVentButton,#incineratorButton,#rearWindowButton').forEach(x=>x.style.display='none');qa('#lichi,#pancake,#nemka,#delta,#kashatan,#charlotte,#lizka,#mindflayer').forEach(x=>x.style.display='none');$('cameraNemkaEyes').classList.remove('nemkaEyesActive');$('nemkaEyes').classList.remove('nemkaEyesActive');$('cameraAlarm').disabled=false;}
function tick(){if(!playing)return;elapsed++;updateTime();ai();if(elapsed>=360)win()}
function updateTime(){let h=Math.floor(elapsed/60);let m=elapsed%60;let label=h===0?'12':String(h);$('time').textContent=`${label}:${String(m).padStart(2,'0')} AM`}
function ai(){let h=Math.floor(elapsed/60);if(active('nemka')&&elapsed>=60){state.nemka+=.045;if(state.nemka>45&&state.nemka<65){$('cameraNemkaEyes').classList.add('nemkaEyesActive');}else{$('cameraNemkaEyes').classList.remove('nemkaEyesActive')}if(state.nemka>=80&&!backupDone){powerOff() }else if(backupDone&&state.nemka>=100){if(rightDoorClosed)state.nemka=70;else lose('Немка добралась до правого коридора.')}}
if(active('lichi')){state.lichi+=.035;if(state.lichi>70&&view==='left')$('lichi').style.display='block';if(state.lichi>=100)lose('Личи добралась до левого коридора. Используй вспышку.');}
if(active('pancake')&&elapsed>=120){state.pancake+=.028;if(state.pancake>=100)lose('Панкейк пробрался через вентиляцию.');}
if(active('kyu')){state.kyu+=.022;if(state.kyu>=100&&!rightDoorClosed)lose('Кью добрался до офиса.');if(rightDoorClosed&&state.kyu>=80)state.kyu=45}
if(active('kashatan')){state.kashatan+=.06;if(state.kashatan>=100&&!windowPowered())lose('Каштан добрался до заднего окна.');if(windowPowered()&&state.kashatan>=80)state.kashatan=35}
if(active('charlotte')){state.charlotte+=.055;if(state.charlotte>=100){if(Date.now()<energyBlockedUntil){}else if(windowPowered()){energyBlockedUntil=Date.now()+20000;energy='camera';updateEnergyUI();state.charlotte=35;status('Шарлота заблокировала питание окна на 20 секунд!')}else lose('Шарлота добралась до заднего окна.');}}
if(active('lizka')){state.lizka+=.035;if(state.lizka>=100&&!fencePowered())lose('Лизка добралась до резервного питания.');if(fencePowered()&&state.lizka>=80)state.lizka=30}
if(active('delta')&&elapsed>=120){state.delta+=.035;if(state.delta>=100&&!incineratorPowered())lose('Дельта пробралась через вентиляцию.');if(incineratorPowered()&&state.delta>=70)state.delta=20;showVentControls()}
if(active('mindflayer')){state.mindflayer+=.025;if(state.mindflayer>=100)openMindPanel();}
renderAI()}
function renderAI(){if(view==='left'&&active('lichi')&&state.lichi>55){$('lichi').style.display='block';$('lichi').style.left='45%';$('lichi').style.top='55%'}else $('lichi').style.display='none';if(view==='front'&&active('pancake')&&state.pancake>55){$('pancake').style.display='block';$('pancake').style.left='50%';$('pancake').style.top='65%'}else $('pancake').style.display='none';if(view==='right'&&active('nemka')&&backupDone&&state.nemka>65){$('nemka').style.display='block';$('nemka').style.left='78%';$('nemka').style.top='50%'}else $('nemka').style.display='none';if(view==='rear'&&active('kashatan')&&state.kashatan>45){$('kashatan').style.display='block';$('kashatan').style.left='50%';$('kashatan').style.top='48%'}else $('kashatan').style.display='none';if(view==='rear'&&active('charlotte')&&state.charlotte>45){$('charlotte').style.display='block';$('charlotte').style.left='52%';$('charlotte').style.top='45%'}else $('charlotte').style.display='none';}
function status(t){$('status').textContent=t}
function powerOff(){if(backupDone)return;backupDone=true;snd('powerOffAudio');$('backupPanel').classList.remove('hidden');status('ОСНОВНОЕ ПИТАНИЕ ОТКЛЮЧЕНО');}
function windowPowered(){return energy==='window'&&Date.now()>=energyBlockedUntil&&!energyBusy}
function fencePowered(){return energy==='fence'&&Date.now()>=energyBlockedUntil&&!energyBusy}
function incineratorPowered(){return energy==='incinerator'&&Date.now()>=energyBlockedUntil&&!energyBusy}
function openMindPanel(){if(!$('mindPanel').classList.contains('hidden'))return;$('mindPanel').classList.remove('hidden');mindLevel=70;updateMind();clearInterval(mindTimer);mindTimer=setInterval(()=>{mindLevel-=1.1;if(mindLevel<=0){mindLevel=0;clearInterval(mindTimer);$('mindPanel').classList.add('hidden');state.mindflayer=20;status('Майндфлеиер полностью замедлен.')}updateMind()},500)}
function updateMind(){$('mindBarFill').style.width=mindLevel+'%';$('mindMessage').textContent='Скорость: '+(mindLevel>55?'высокая':mindLevel>25?'средняя':'низкая')}
function showVentControls(){if(!active('delta')||elapsed<120)return;$('upperVentButton').style.display='block';$('incineratorButton').style.display='block'}
function setView(v){view=v;status(v==='left'?'ЛЕВЫЙ КОРИДОР':v==='right'?'ПРАВЫЙ КОРИДОР':v==='rear'?'ЗАДНЕЕ ОКНО':'ОФИС');$('rearWindowButton').style.display=v==='rear'?'block':'none';$('upperVentButton').style.display=(v==='front'&&active('delta')&&elapsed>=120)?'block':'none';renderAI()}
function flash(){snd('flashAudio');$('flash').style.opacity=1;setTimeout(()=>$('flash').style.opacity=0,100);if(active('lichi')&&state.lichi>40){state.lichi=Math.max(0,state.lichi-45);status('Личи отпугнута вспышкой.')}}
function openCamera(){if(energy!=='camera'){status('Камеры не получают питание!');return}$('cameraPanel').classList.remove('hidden');updateCamera()}
function updateCamera(){let b=q(`[data-camera="${camera}"]`);qa('#cameraMap button[data-camera]').forEach(x=>x.classList.remove('energyTargetActive'));if(b)b.classList.add('energyTargetActive');$('cameraNumber').textContent=camera.toUpperCase();$('cameraImage').style.backgroundImage=`url("images/${camera}.png")`;$('cameraLichi').style.display=active('lichi')&&camera==='cam02'&&state.lichi>20?'block':'none';$('cameraPancake').style.display=active('pancake')&&camera==='cam04'&&state.pancake>15?'block':'none';$('cameraNemkaEyes').classList.toggle('nemkaEyesActive',active('nemka')&&state.nemka>35&&camera===`cam0${Math.max(1,Math.min(7,Math.ceil(state.nemka/12)))}`);$('catMessage').textContent='Текущая камера: '+camera.toUpperCase()}
function meow(){if(energy!=='camera'){status('Камеры обесточены.');return}if(active('nemka')&&state.nemka>10&&state.nemka<80){state.nemka=Math.max(0,state.nemka-28);snd('catAudio');$('catMessage').textContent='Немка отвлечена мяуканьем!';status('Мяуканье воспроизведено.')}else{$('catMessage').textContent='Мяуканье воспроизведено.';snd('catAudio')}}
function alarm(){if(energy!=='camera'){status('Сирена не работает без энергии.');return}if(active('charlotte')&&state.charlotte>10&&state.charlotte<100){state.charlotte=Math.max(0,state.charlotte-45);status('СИРЕНА: Шарлота отвлечена!')}snd('sirenAudio')}
function upperVent(){if(elapsed<120)return;$('upperVent').classList.toggle('upperVentActive');if($('upperVent').classList.contains('upperVentActive')){status('ВЕРХНЯЯ ШАХТА');if(active('delta')&&state.delta>40)showDelta(true)}else{status('ОФИС');showDelta(false)}}
function showDelta(x){$('delta').style.display=x?'block':'none';if(x){$('delta').style.left='50%';$('delta').style.top='45%'}}
function burn(){if(energy!=='incinerator'){status('Сначала направьте энергию на сжигатель.');return}snd('burnAudio');if(active('delta'))state.delta=Math.max(0,state.delta-65);status('Мусор сожжён. Дельта отступает.');}
function rear(){setView('rear');$('rearWindow').style.display='block';setTimeout(()=>{$('rearWindow').style.display='none'},200)}
function closeRight(){rightDoorClosed=!rightDoorClosed;$('rightDoor').classList.toggle('closed',rightDoorClosed);$('rightDoorButton').textContent=rightDoorClosed?'ОТКРЫТЬ':'ЗАКРЫТЬ';status(rightDoorClosed?'ПРАВАЯ ДВЕРЬ ЗАКРЫТА':'ПРАВАЯ ДВЕРЬ ОТКРЫТА')}
function selectEnergy(e){if(Date.now()<energyBlockedUntil){status('Питание окна временно заблокировано.');return}energy=e;updateEnergyUI()}
function updateEnergyUI(){const names={camera:'КАМЕРЫ',window:'ОКНО',incinerator:'СЖИГАТЕЛЬ',fence:'ЭЛЕКТРОЗАБОР',door:'ПРАВАЯ ДВЕРЬ'};$('energyTargetText').textContent=names[energy];$('energyMessage').textContent='Энергия направлена на '+names[energy].toLowerCase()+'.';qa('#energyTargets button').forEach(b=>b.classList.toggle('energyTargetActive',b.dataset.energy===energy))}
function leverDown(){if(energyBusy)return;leverStart=Date.now();energyBusy=true;const loop=setInterval(()=>{let p=Math.min(100,(Date.now()-leverStart)/20);$('leverProgressBar').style.width=p+'%';if(p>=100){clearInterval(loop);energyBusy=false;$('leverProgressBar').style.width='0';updateEnergyUI();status('Перенаправление завершено.')}} ,30)}
function backupWire(n){n=Number(n);if(n===wireStep+1){wireStep++;q(`[data-wire="${n}"]`).classList.add('wireSelected');if(wireStep===4){backupDone=true;$('backupPanel').classList.add('hidden');state.nemka=65;snd('backupAudio');status('Резервная система запущена!')}}else{wireStep=0;qa('#backupWires button').forEach(x=>x.classList.remove('wireSelected'));$('backupMessage').textContent='Ошибка! Начните заново.'}}
function lose(reason){if(!playing)return;playing=false;clearInterval(timer);clearInterval(mindTimer);stop('humAudio');$('loseReason').textContent=reason;$('gameOver').classList.remove('hidden')}
function win(){playing=false;clearInterval(timer);clearInterval(mindTimer);stop('humAudio');let unlocked=Math.min(13,night+1);localStorage.setItem('bgnUnlocked',unlocked);$('winText').textContent='NIGHT '+night+' COMPLETE';$('nextNight').style.display=night<13?'block':'none';$('winScreen').classList.remove('hidden')}
function fillNights(){let u=Number(localStorage.getItem('bgnUnlocked')||1);$('nightsList').innerHTML='';for(let i=1;i<=13;i++){let b=document.createElement('button');b.className='nightButton'+(i>u?' locked':'');b.textContent='NIGHT '+i;b.disabled=i>u;b.onclick=()=>start(i);$('nightsList').appendChild(b)}}
$('startGameButton').onclick=()=>start(Number(localStorage.getItem('bgnUnlocked')||1));$('nightsButton').onclick=()=>{fillNights();hideAll();$('nightsMenu').classList.remove('hidden')};$('closeNights').onclick=menu;$('settingsButton').onclick=()=>{hideAll();$('settingsMenu').classList.remove('hidden')};$('closeSettings').onclick=menu;$('skipPhoneButton').onclick=begin;$('fullscreenButton').onclick=()=>document.documentElement.requestFullscreen?.();$('resetProgress').onclick=()=>{localStorage.removeItem('bgnUnlocked');fillNights();status('Прогресс сброшен.')};$('cameraButton').onclick=openCamera;$('closeCameraPanel').onclick=()=>$('cameraPanel').classList.add('hidden');$('energyButton').onclick=()=>{updateEnergyUI();$('energyPanel').classList.remove('hidden')};$('closeEnergyPanel').onclick=()=>$('energyPanel').classList.add('hidden');$('closeMindPanel').onclick=()=>$('mindPanel').classList.add('hidden');$('flashButton').onclick=flash;$('leftButton').onclick=()=>setView('left');$('frontButton').onclick=()=>setView('front');$('rightButton').onclick=()=>setView('right');$('rightDoorButton').onclick=closeRight;$('rearWindowButton').onclick=rear;$('upperVentButton').onclick=upperVent;$('incineratorButton').onclick=burn;$('catMeowButton').onclick=meow;$('cameraAlarm').onclick=alarm;$('mindSlow').onclick=()=>{mindLevel=Math.max(0,mindLevel-15);updateMind();if(mindLevel===0){clearInterval(mindTimer);$('mindPanel').classList.add('hidden');state.mindflayer=10;status('Майндфлеиер полностью замедлен.')}};$('mindFast').onclick=()=>{mindLevel=Math.min(100,mindLevel+20);updateMind()};qa('#cameraMap button[data-camera]').forEach(b=>b.onclick=()=>{camera=b.dataset.camera;updateCamera()});qa('#energyTargets button').forEach(b=>b.onclick=()=>selectEnergy(b.dataset.energy));qa('#backupWires button').forEach(b=>b.onclick=()=>backupWire(b.dataset.wire));$('lever').addEventListener('pointerdown',leverDown);$('restart').onclick=()=>begin();$('menuAfterLose').onclick=menu;$('nextNight').onclick=()=>start(Math.min(13,night+1));$('menuAfterWin').onclick=menu;fillNights();
